# Generated by Django 3.0.4 on 2020-03-11 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joined:'),
            preserve_default=False,
        ),
    ]
