# Generated by Django 3.0.4 on 2020-03-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200311_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='join_date',
        ),
    ]
