# Generated by Django 3.0.4 on 2020-03-11 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_person_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
