# Generated by Django 3.0.4 on 2020-03-11 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200311_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 11, 12, 0, 58, 883497, tzinfo=utc)),
        ),
    ]
