# Generated by Django 3.0.4 on 2020-03-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20200311_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateTimeField(verbose_name='Data dołączenia'),
        ),
    ]
