# Generated by Django 3.0.4 on 2020-03-11 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20200311_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Data dołączenia'),
        ),
    ]
