# Generated by Django 3.0.4 on 2020-03-11 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20200311_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Imie',
            new_name='Imię',
        ),
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data dołączenia'),
        ),
    ]
