# Generated by Django 3.0.4 on 2020-03-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_contacttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacttype',
            old_name='znajomy',
            new_name='person',
        ),
    ]
