# Generated by Django 3.0.4 on 2020-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_auto_20200311_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttype',
            name='contact',
            field=models.CharField(blank=True, choices=[('ZNAJOMY', 'Znajomy'), ('RODZINA', 'Rodzina'), ('INTERNET', 'Internet')], max_length=50),
        ),
    ]
