# Generated by Django 3.0.4 on 2020-03-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_contacttype_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacttype',
            old_name='contact',
            new_name='TypKontaktu',
        ),
    ]
