# Generated by Django 3.0.4 on 2020-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_auto_20200311_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='TypKontaktu',
            field=models.CharField(blank=True, choices=[('ZNAJOMY', 'Znajomy'), ('RODZINA', 'Rodzina'), ('INTERNET', 'Internet')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ContactType',
        ),
    ]
