# Generated by Django 3.0.4 on 2020-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_auto_20200311_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Status',
            field=models.CharField(blank=True, choices=[('ZNAJOMY', 'Znajomy'), ('RODZINA', 'Rodzina'), ('INTERNET', 'Internet')], max_length=50),
        ),
    ]
