# Generated by Django 3.0.4 on 2020-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Status',
            field=models.CharField(blank=True, choices=[('NOWY', 'Nowy'), ('ZAINTERESOWANY', 'Zainteresowany'), ('NIEZAINTERESOWANY', 'Niezainteresowany'), ('ZAWIESZONY', 'Zawieszony')], max_length=50),
        ),
    ]
