# Generated by Django 3.0.4 on 2020-03-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_auto_20200311_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Klient',
        ),
    ]
