# Generated by Django 3.0.4 on 2020-03-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_auto_20200312_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klient',
            new_name='Klienci',
        ),
    ]
