# Generated by Django 3.0.4 on 2020-03-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_auto_20200312_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='klienci',
            name='Status',
            field=models.CharField(blank=True, choices=[('NOWY', 'Nowy'), ('ZAINTERESOWANY', 'Zainteresowany'), ('NIEZAINTERESOWANY', 'Niezainteresowany'), ('ZAWIESZONY', 'Zawieszony')], max_length=50),
        ),
        migrations.AddField(
            model_name='klienci',
            name='TypKontaktu',
            field=models.CharField(blank=True, choices=[('ZNAJOMY', 'Znajomy'), ('RODZINA', 'Rodzina'), ('INTERNET', 'Internet')], max_length=50),
        ),
    ]
