# Generated by Django 3.0.4 on 2020-03-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_auto_20200312_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klienci',
            old_name='TypKontaktu',
            new_name='Kontakt',
        ),
    ]
