# Generated by Django 3.0.4 on 2020-03-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_auto_20200312_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klienci',
            name='Kontakt',
        ),
        migrations.AddField(
            model_name='klienci',
            name='Contact',
            field=models.CharField(blank=True, choices=[('ZNAJOMY', 'Znajomy'), ('RODZINA', 'Rodzina'), ('INTERNET', 'Internet')], max_length=50, verbose_name='Typ kontaktu'),
        ),
        migrations.AlterField(
            model_name='klienci',
            name='Status',
            field=models.CharField(blank=True, choices=[('NOWY', 'Nowy'), ('ZAINTERESOWANY', 'Zainteresowany'), ('NIEZAINTERESOWANY', 'Niezainteresowany'), ('ZAWIESZONY', 'Zawieszony')], max_length=50, verbose_name='Status klienta'),
        ),
    ]
